[package]
name = "soros-vote-api"
version = "1.1.2"
description = "Soros Vote program API"
authors = ["Soros Maintainers <maintainers@soros.com>"]
repository = "https://github.com/soros-labs/soros"
license = "Apache-2.0"
homepage = "https://soros.com/"
edition = "2018"

[dependencies]
bincode = "1.1.3"
log = "0.4.2"
serde = "1.0.90"
serde_derive = "1.0.90"
soros-logger = { path = "../../logger", version = "1.1.2"   }
soros-metrics = { path = "../../metrics", version = "1.1.2"   }
soros-sdk = { path = "../../sdk", version = "1.1.2"   }

[dev-dependencies]
soros-runtime = { path = "../../runtime", version = "1.1.2"   }

[lib]
name = "soros_vote_api"
crate-type = ["lib"]
