[package]
name = "buffett-fullnode"
version = "0.1.0"
authors = ["Caesar Chad <BLUE.WEB.GEEK@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
getopts = "0.2"
log = "0.4.2"
serde_json = "1.0.10"
buffett-core = { path = "../core" }