[package]
name = "soros-stake-program"
version = "0.14.2"
description = "Soros stake program"
authors = ["Soros Maintainers <maintainers@soros.com>"]
repository = "https://github.com/soros-labs/soros"
license = "Apache-2.0"
homepage = "https://soros.com/"
edition = "2018"

[dependencies]
log = "0.4.2"
soros-logger = { path = "../../logger", version = "0.14.2"   }
soros-sdk = { path = "../../sdk", version = "0.14.2"   }
soros-stake-api = { path = "../stake_api", version = "0.14.2"   }

[lib]
name = "soros_stake_program"
crate-type = ["cdylib"]

