[package]
name = "soros-bpfloader"
version = "0.12.3"
description = "Bitconch BPF Loader"
authors = ["Bitconch Dev Team"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io"
edition = "2018"

[dependencies]
bincode = "1.1.2"
byteorder = "1.3.1"
libc = "0.2.50"
log = "0.4.2"
soros_rbpf = "=0.1.10"
serde = "1.0.89"
soros-logger = { path = "../../logger", version = "0.12.3" }
soros-sdk = { path = "../../sdk", version = "0.12.3" }

[lib]
name = "soros_bpf_loader"
crate-type = ["lib", "cdylib"]
