
# Note: This crate must be built using build.sh

[package]
name = "soros-bpf-rust-noop"
version = "1.1.2"
description = "Soros BPF noop program written in Rust"
authors = ["Caesar Chad <caesar@bitconch.io>"]
repository = "https://github.com/caesarchad/rustelo-rust"
license = "Apache-2.0"
homepage = "https://bitconch.io/"

[dependencies]
# byteorder = { version = "1.3.1", default-features = false }
# heapless = { version = "0.4.0", default-features = false }
# byte = { version = "0.2", default-features = false }

[workspace]
members = []

[lib]
name = "soros_bpf_rust_noop"
crate-type = ["cdylib"]


