
# Note: This crate must be built using build.sh

[package]
name = "soros-bpf-rust-noop"
version = "0.14.2"
description = "Soros BPF noop program written in Rust"
authors = ["Soros Maintainers <maintainers@soros.com>"]
repository = "https://github.com/soros-labs/soros"
license = "Apache-2.0"
homepage = "https://soros.com/"

[dependencies]
# byteorder = { version = "1.3.1", default-features = false }
# heapless = { version = "0.4.0", default-features = false }
# byte = { version = "0.2", default-features = false }

[workspace]
members = []

[lib]
name = "soros_bpf_rust_noop"
crate-type = ["cdylib"]


