[package]
name = "rustelo_easy"
publish = false
version = "0.0.0"
edition = "2018"
description = "Call Rust Code in Go, in an easy way."

[lib]
crate-type = ["cdylib"] # refer to https://doc.rust-lang.org/reference/linkage.html
                           # staticlib means a static library will be built 
                           # The static library is actually an *.a archive on linux and osx 
                           #                                    and a *.lib file on windows. 
                           # This format is recommended for use in situations such as linking Rust code
                           # into an existing non-Rust application because it will not have dynamic dependencies on other Rust code.
                           # cdylib means a dynamic system library will be produced. 

[dependencies] #includes some dependencies
#some_project_on_git = { git = "https://github.com/some_project_on_git", rev = "bab20f4d2f2499dc1f2af83ad9a76e39fc1be532" <-the hash of the branch }
atty = "0.2"
bincode = "1.0.0"
bs58 = "0.2.0"
byteorder = "1.2.1"
bytes = "0.4"
chrono = { version = "0.4.0", features = ["serde"] }
clap = "2.32.0"
dirs = "1.0.2"
elf = "0.0.10"
env_logger = "0.5.12"
generic-array = { version = "0.12.0", default-features = false, features = ["serde"] }
getopts = "0.2"
hex-literal = "0.1.1"
influx_db_client = "0.3.6"
ipnetwork = "0.12.7"
itertools = "0.7.8"
libc = "0.2.43"
libloading = "0.5.0"
log = "0.4.2"
matches = "0.1.6"
nix = "0.11.0"
pnet_datalink = "0.21.0"
rand = "0.5.1"
rayon = "1.0.0"
reqwest = "0.9.0"
ring = "0.13.2"
sha2 = "0.8.0"
serde = "1.0.27"
serde_cbor = "0.9.0"
serde_derive = "1.0.27"
serde_json = "1.0.10"
socket2 = "0.3.8"
sys-info = "0.5.6"
tokio = "0.1"
tokio-codec = "0.1"
untrusted = "0.6.2"
slotmap = "0.3"
once_cell = "0.1.6"
failure = "0.1.3"
parking_lot = {version = "0.7.1"}
mbox = "0.5.0"
paste = "0.1"
buffett = {path="buffett"}

#solana-sdk = { path = "sdk", version = "0.10.0" }
#solana-jsonrpc-core = "0.3.0"
#solana-jsonrpc-http-server = "0.3.0"
#solana-jsonrpc-macros = "0.3.0"
#solana-jsonrpc-pubsub = "0.3.0"
#solana-jsonrpc-ws-server = "0.3.0"
#solana-noop = { path = "programs/native/noop", version = "0.10.0" }
#solana-bpfloader = { path = "programs/native/bpf_loader", version = "0.10.0" }
#solana-lualoader = { path = "programs/native/lua_loader", version = "0.10.0" }

[profile.release]
lto = true                   #Link Time Optimization for LLVM, reduce size, increase compilation time
codegen-units = 1            #code generation units  (the current default) when using rustc with
                             #--opt-level=2 (a.k.a -O) or --opt-level=3.
                             # opt-level means Optimization Level for LLVM, can refer to this 
                             # http://clang-developers.42468.n3.nabble.com/Meaning-of-LLVM-optimization-levels-td4032493.html#a4032674
panic = 'abort'
incremental = false
debug = true