[package]
name = "bitconch-bpfloader"
version = "0.12.0"
description = "Bitconch BPF Loader"
authors = ["Bitconch Dev <info@bitconch.io>"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io/"
edition = "2018"

[features]
bpf_c = []
bpf_rust = []

[dependencies]
bincode = "1.1.2"
byteorder = "1.3.1"
elf = "0.0.10"
libc = "0.2.49"
log = "0.4.2"
bitconch_rbpf = "=0.1.10"
serde = "1.0.88"
bitconch-logger = { path = "../../../logger", version = "0.12.0" }
bitconch-sdk = { path = "../../../sdk", version = "0.12.0" }

[build-dependencies]
walkdir = "2"

[lib]
name = "bitconch_bpf_loader"
crate-type = ["lib", "cdylib"]

[[bench]]
name = "bpf_loader"

