[package]
name = "soros-budget-api"
version = "0.12.3"
description = "Bitconch Budget program API"
authors = ["Bitconch Dev Team"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io"
edition = "2018"

[dependencies]
bincode = "1.1.2"
chrono = { version = "0.4.0", features = ["serde"] }
serde = "1.0.89"
serde_derive = "1.0.89"
soros-sdk = { path = "../../sdk", version = "0.12.3" }

[lib]
name = "soros_budget_api"
crate-type = ["lib"]
