[package]
name = "soros-budget-api"
version = "0.14.2"
description = "Soros Budget program API"
authors = ["Soros Maintainers <maintainers@soros.com>"]
repository = "https://github.com/soros-labs/soros"
license = "Apache-2.0"
homepage = "https://soros.com/"
edition = "2018"

[dependencies]
bincode = "1.1.3"
chrono = { version = "0.4.0", features = ["serde"] }
log = "0.4.2"
num-derive = "0.2"
num-traits = "0.2"
serde = "1.0.90"
serde_derive = "1.0.90"
soros-sdk = { path = "../../sdk", version = "0.14.2"   }

[dev-dependencies]
soros-runtime = { path = "../../runtime", version = "0.14.2"   }

[lib]
name = "soros_budget_api"
crate-type = ["lib"]
