[v1]
"soros-bench-tps 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/bench-tps)" = ["soros-bench-tps"]
"soros-drone 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/drone)" = ["soros-drone"]
"soros-fullnode 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/fullnode)" = ["soros-fullnode"]
"soros-genesis 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/genesis)" = ["soros-genesis"]
"soros-gossip 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/gossip)" = ["soros-gossip"]
"soros-install 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/install)" = ["soros-install"]
"soros-keygen 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/keygen)" = ["soros-keygen"]
"soros-ledger-tool 0.14.0 (path+file:///home/ben/Downloads/rustelo-rust/soros/ledger-tool)" = ["soros-ledger-tool"]
"soros-wallet 1.1.2 (path+file:///home/ben/Downloads/rustelo-rust/soros/wallet)" = ["soros-wallet"]
