[package]
name = "soros-exchange-api"
version = "1.1.2"
description = "Soros Exchange program API"
authors = ["Caesar Chad <caesar@bitconch.io>"]
repository = "https://github.com/caesarchad/rustelo-rust"
license = "Apache-2.0"
homepage = "https://bitconch.io/"
edition = "2018"

[dependencies]
log = "0.4.2"
bincode = "1.1.3"
serde = "1.0.90"
serde_derive = "1.0.90"
soros-logger = { path = "../../logger", version = "1.1.2"   }
soros-sdk = { path = "../../sdk", version = "1.1.2"   }
soros-metrics = { path = "../../metrics", version = "1.1.2"   }

[dev-dependencies]
soros-runtime = { path = "../../runtime", version = "1.1.2"   }

[lib]
name = "soros_exchange_api"
crate-type = ["lib"]
