[package]
name = "bitconch-native-loader"
version = "0.12.0"
description = "Bitconch Native Loader"
authors = ["Bitconch Dev <info@bitconch.io>"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io/"
edition = "2018"

[dependencies]
bincode = "1.1.1"
libc = "0.2.48"
libloading = "0.5.0"
log = "0.4.2"
bitconch-sdk = { path = "../../../sdk", version = "0.12.0" }

[lib]
name = "bitconch_native_loader"
crate-type = ["lib"]
