[package]
name = "print"
version = "0.1.0"
authors = ["Bitconch Dev"]

[dependencies]
buffett_program_interface = { path = "../../../common" }

[lib]
name = "print"
crate-type = ["dylib"]

