[package]
name = "bitconch-runtime"
version = "0.12.0"
description = "Bitconch runtime"
authors = ["Bitconch Dev <info@bitconch.io>"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io/"
edition = "2018"

[dependencies]
bincode = "1.1.2"
bv = { version = "0.11.0", features = ["serde"] }
fnv = "1.0.6"
hashbrown = "0.1.8"
log = "0.4.2"
rand = "0.6.5"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_json = "1.0.38"
bitconch-metrics = { path = "../metrics", version = "0.12.0" }
bitconch-sdk = { path = "../sdk", version = "0.12.0" }
bitconch-native-loader = { path = "../programs/native/native_loader", version = "0.12.0" }
bitconch-system-program = { path = "../programs/native/system", version = "0.12.0" }

[lib]
name = "bitconch_runtime"
crate-type = ["lib"]

