[package]
name = "soros-failure-program"
version = "1.1.2"
description = "Soros failure program"
authors = ["Soros Maintainers <maintainers@soros.com>"]
repository = "https://github.com/soros-labs/soros"
license = "Apache-2.0"
homepage = "https://soros.com/"
edition = "2018"

[dependencies]
soros-sdk = { path = "../../sdk", version = "1.1.2"   }
log = "0.4.2"

[dev-dependencies]
soros-runtime = { path = "../../runtime", version = "1.1.2"   }

[lib]
name = "soros_failure_program"
crate-type = ["cdylib"]

