[package]
name = "soros-failure-program"
version = "1.1.2"
description = "Soros failure program"
authors = ["Caesar Chad <caesar@bitconch.io>"]
repository = "https://github.com/caesarchad/rustelo-rust"
license = "Apache-2.0"
homepage = "https://bitconch.io/"
edition = "2018"

[dependencies]
soros-sdk = { path = "../../sdk", version = "1.1.2"   }
log = "0.4.2"

[dev-dependencies]
soros-runtime = { path = "../../runtime", version = "1.1.2"   }

[lib]
name = "soros_failure_program"
crate-type = ["cdylib"]

