[package]
name = "move_funds"
version = "0.1.0"
authors = ["Bitconch Dev"]

[dependencies]
bincode = "1.0.0"
generic-array = { version = "0.12.0", default-features = false, features = ["serde"] }
buffett-interface = "0.1.0"

[lib]
name = "move_funds"
crate-type = ["dylib"]

