[package]
name = "soros-upload-perf"
version = "0.12.3"
description = "Metrics Upload Utility"
authors = ["Bitconch Dev Team"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
edition = "2018"
homepage = "https://bitconch.io"

[dependencies]
serde_json = "1.0.39"
soros-metrics = { path = "../metrics", version = "0.12.3" }

[[bin]]
name = "soros-upload-perf"
path = "src/upload-perf.rs"

