[package]
name = "bitconch-upload-perf"
version = "0.12.0"
description = "Metrics Upload Utility"
authors = ["Bitconch Dev <info@bitconch.io>"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
edition = "2018"
homepage = "https://bitconch.io/"

[dependencies]
serde_json = "1.0.38"
bitconch-metrics = { path = "../metrics", version = "0.12.0" }

[[bin]]
name = "bitconch-upload-perf"
path = "src/upload-perf.rs"

