[package]
name = "soros-storage-program"
version = "1.1.2"
description = "Soros storage program"
authors = ["Soros Maintainers <maintainers@soros.com>"]
repository = "https://github.com/soros-labs/soros"
license = "Apache-2.0"
homepage = "https://soros.com/"
edition = "2018"

[dependencies]
log = "0.4.2"
soros-logger = { path = "../../logger", version = "1.1.2"   }
soros-sdk = { path = "../../sdk", version = "1.1.2"   }
soros-storage-api = { path = "../storage_api", version = "1.1.2"   }

[lib]
name = "soros_storage_program"
crate-type = ["cdylib"]

