[package]
name = "soros-failure"
version = "0.12.3"
description = "Bitconch failure program"
authors = ["Bitconch Dev Team"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io"
edition = "2018"

[dependencies]
soros-sdk = { path = "../../sdk", version = "0.12.3" }
log = "0.4.2"

[dev-dependencies]
soros-runtime = { path = "../../runtime", version = "0.12.3" }

[lib]
name = "failure"
crate-type = ["cdylib"]

