[workspace]
members = [
   "benchbot",
   "interface",
   "core",
    "tokenbot",
    "fullnode",
    "fullnode-config",
    "genesis",
    "keybot",
    "ledgerbot",
    "budget",
    "timing",
    "crypto",
    "metrics",
]