[package]
name = "soros-vote-program"
version = "0.12.3"
description = "Bitconch vote program"
authors = ["Bitconch Dev Team"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io"
edition = "2018"

[dependencies]
bincode = "1.1.2"
log = "0.4.2"
soros-logger = { path = "../../logger", version = "0.12.3" }
soros-metrics = { path = "../../metrics", version = "0.12.3" }
soros-sdk = { path = "../../sdk", version = "0.12.3" }
soros-vote-api = { path = "../vote_api", version = "0.12.3" }

[dev-dependencies]
soros-runtime = { path = "../../runtime", version = "0.12.3" }

[lib]
name = "soros_vote_program"
crate-type = ["cdylib"]

