[package]
name = "soros"
description = "Blockchain, Rebuilt for Scale"
version = "0.12.3"
documentation = "https://docs.rs/bitconch"
homepage = "https://bitconch.io"
readme = "../README.md"
repository = "https://github.com/bitconch/bus"
authors = ["Bitconch Dev Team"]
license = "Apache-2.0"
edition = "2018"

[badges]
codecov = { repository = "bitconch/soros", branch = "master", service = "github" }

[features]
chacha = []
cuda = []
erasure = []
kvstore = ["memmap"]

[dependencies]
bincode = "1.1.2"
bs58 = "0.2.0"
byteorder = "1.3.1"
chrono = { version = "0.4.0", features = ["serde"] }
hashbrown = "0.1.8"
indexmap = "1.0"
itertools = "0.8.0"
jsonrpc-core = "10.1.0"
jsonrpc-derive = "10.1.0"
jsonrpc-http-server = "10.1.0"
jsonrpc-pubsub = "10.1.0"
jsonrpc-ws-server = "10.1.0"
libc = "0.2.50"
log = "0.4.2"
memmap = { version = "0.7.0", optional = true }
nix = "0.13.0"
rand = "0.6.5"
rand_chacha = "0.1.1"
rayon = "1.0.0"
ring = "0.13.2"
rocksdb = "0.11.0"
serde = "1.0.89"
serde_derive = "1.0.88"
serde_json = "1.0.39"
soros-budget-api = { path = "../programs/budget_api", version = "0.12.3" }
soros-client = { path = "../client", version = "0.12.3" }
soros-drone = { path = "../drone", version = "0.12.3" }
soros-logger = { path = "../logger", version = "0.12.3" }
soros-metrics = { path = "../metrics", version = "0.12.3" }
soros-netutil = { path = "../netutil", version = "0.12.3" }
soros-runtime = { path = "../runtime", version = "0.12.3" }
soros-sdk = { path = "../sdk", version = "0.12.3" }
soros-storage-api = { path = "../programs/storage_api", version = "0.12.3" }
soros-vote-api = { path = "../programs/vote_api", version = "0.12.3" }
soros-vote-signer = { path = "../vote-signer", version = "0.12.3" }
sys-info = "0.5.6"
tokio = "0.1"
tokio-codec = "0.1"
untrusted = "0.6.2"

[dev-dependencies]
hex-literal = "0.1.3"
matches = "0.1.6"
soros-vote-program = { path = "../programs/vote", version = "0.12.3" }
soros-budget-program = { path = "../programs/budget", version = "0.12.3" }
