[package]
authors = ["Bitconch Dev <info@bitconch.io>"]
edition = "2018"
name = "bitconch-wallet"
description = "Blockchain, Rebuilt for Scale"
version = "0.12.0"
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io/"

[dependencies]
bincode = "1.1.1"
bs58 = "0.2.0"
clap = "2.32.0"
chrono = { version = "0.4.0", features = ["serde"] }
dirs = "1.0.2"
serde_json = "1.0.38"
bitconch = { path = "..", version = "0.12.0" }
bitconch-drone = { path = "../drone", version = "0.12.0" }
bitconch-logger = { path = "../logger", version = "0.12.0" }
bitconch-sdk = { path = "../sdk", version = "0.12.0" }
bitconch-vote-signer = { path = "../vote-signer", version = "0.12.0" }

[features]
cuda = ["bitconch/cuda"]
