[package]
name = "bitconch-vote-program"
version = "0.12.0"
description = "Bitconch vote program"
authors = ["Bitconch Dev <info@bitconch.io>"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io/"
edition = "2018"

[dependencies]
bincode = "1.1.1"
log = "0.4.2"
bitconch-logger = { path = "../../../logger", version = "0.12.0" }
bitconch-metrics = { path = "../../../metrics", version = "0.12.0" }
bitconch-sdk = { path = "../../../sdk", version = "0.12.0" }

[dev-dependencies]
bitconch-runtime = { path = "../../../runtime", version = "0.12.0" }

[lib]
name = "bitconch_vote_program"
crate-type = ["cdylib"]

