[package]
name = "soros-token-program"
version = "1.1.2"
description = "Soros token program"
authors = ["Caesar Chad <caesar@bitconch.io>"]
repository = "https://github.com/caesarchad/rustelo-rust"
license = "Apache-2.0"
homepage = "https://bitconch.io/"
edition = "2018"

[dependencies]
log = "0.4.2"
soros-logger = { path = "../../logger", version = "1.1.2"   }
soros-sdk = { path = "../../sdk", version = "1.1.2"   }
soros-token-api = { path = "../token_api", version = "1.1.2"   }

[lib]
name = "soros_token_program"
crate-type = ["cdylib"]

