[package]
name = "soros-rewards-api"
version = "0.12.3"
description = "Bitconch rewards API"
authors = ["Bitconch Dev Team"]
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io"
edition = "2018"

[dependencies]
bincode = "1.1.2"
serde = "1.0.89"
serde_derive = "1.0.89"
soros-sdk = { path = "../../sdk", version = "0.12.3" }
soros-vote-api = { path = "../vote_api", version = "0.12.3" }

[lib]
name = "soros_rewards_api"
crate-type = ["lib"]
