[package]
authors = ["Bitconch Dev <info@bitconch.io>"]
edition = "2018"
name = "bitconch-fullnode"
description = "Blockchain, Rebuilt for Scale"
version = "0.12.0"
repository = "https://github.com/bitconch/bus"
license = "Apache-2.0"
homepage = "https://bitconch.io/"

[dependencies]
clap = "2.32.0"
log = "0.4.2"
serde_json = "1.0.38"
bitconch = { path = "..", version = "0.12.0" }
bitconch-drone = { path = "../drone", version = "0.12.0" }
bitconch-fullnode-config = { path = "../fullnode-config", version = "0.12.0" }
bitconch-logger = { path = "../logger", version = "0.12.0" }
bitconch-netutil = { path = "../netutil", version = "0.12.0" }
bitconch-metrics = { path = "../metrics", version = "0.12.0" }
bitconch-sdk = { path = "../sdk", version = "0.12.0" }
bitconch-vote-signer = { path = "../vote-signer", version = "0.12.0" }

[features]
chacha = ["bitconch/chacha"]
cuda = ["bitconch/cuda"]
erasure = ["bitconch/erasure"]
ipv6 = ["bitconch/ipv6"]
unstable = ["bitconch/unstable"]
